apiVersion : apps/v1
kind: Deployment
metadata:
  name: avensonpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avensonpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: avensonpipelinesjavascriptdocker 
    spec:
      containers:
        - name: avensonpipelinesjavascriptdocker 
          image: crsboxavenson.azurecr.io/avensonpipelinesjavascriptdocker
          ports:
          - containerPort: 8080